# fly.toml app configuration file generated for goodtunes on 2024-12-18T20:42:59-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
# postgres://postgres:jMek8SwOv6RU3M5@goodtunes-db.flycast:5432

app = 'goodtunes'
primary_region = 'sjc'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[experimental]
  auto_rollback = true

[build]

[deploy]
#   release_command = 'npx sequelize db:migrate'

[env]
  NODE_ENV = 'production'
  PRIMARY_REGION = 'sjc'

[http_service]
  internal_port = 4000
  force_https = true
  # https://fly.io/docs/launch/autostop-autostart/#how-it-works
  auto_stop_machines = 'off'
  # auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 4000
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '1s'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
