// { trackNum: #, title: "title", albumId: #, createdAt: new Date(), updatedAt: new Date()},


//* Monte's

// { trackNum: 1, title: "Is This Love", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 2, title: "No Woman, No Cry" (Live), albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 3, title: "Could You Be Loved", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 4, title: "Three Little Birds", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 5, title: "Buffalo Soldier", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 6, title: "Get Up, Stand Up", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 7, title: "Stir It Up", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 8, title: "One Love / People Get Ready", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 9, title: "I Shot the Sheriff", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 10, title: "Waiting in Vain", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 11, title: "Redemption Song", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 12, title: "Satisfy My Soul", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 13, title: "Exodus", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 14, title: "Jamming", albumId: #, createdAt: new Date(), updatedAt: new Date()},



//* Brad's

//{ trackNum: 1, title: "I Ain't the One", albumId: "Pronounced 'Lĕh-'nérd 'Skin-'nérd", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 2, title: "Tuesday's Gone", albumId: "Pronounced 'Lĕh-'nérd 'Skin-'nérd", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 3, title: "Gimme Three Steps", albumId: "Pronounced 'Lĕh-'nérd 'Skin-'nérd", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 4, title: "Simple Man", albumId: "Pronounced 'Lĕh-'nérd 'Skin-'nérd", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 5, title: "Mississippi Kid", albumId: "Pronounced 'Lĕh-'nérd 'Skin-'nérd", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 6, title: "Poison Whiskey", albumId: "Pronounced 'Lĕh-'nérd 'Skin-'nérd", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 7, title: "Free Bird", albumId: "Pronounced 'Lĕh-'nérd 'Skin-'nérd", createdAt: new Date(), updatedAt: new Date()},

//{ trackNum: 1, title: "I Was Made for Lovin' You", albumId: "Dynasty", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 2, title: "2,000 Man", albumId: "Dynasty", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 3, title: "Sure Know Something", albumId: "Dynasty", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 4, title: "Dirty Livin' ", albumId: "Dynasty", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 5, title: "Charisma", albumId: "Dynasty", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 6, title: "Magic Touch", albumId: "Dynasty", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 7, title: "Hard Times", albumId: "Dynasty", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 8, title: "X-Ray Eyes", albumId: "Dynasty", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 9, title: "Save Your Love", albumId: "Dynasty", createdAt: new Date(), updatedAt: new Date()},

//{ trackNum: 1, title: "Southern Nights", albumId: "Southern Nights", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 2, title: "This Is Sarah's Song", albumId: "Southern Nights", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 3, title: "For Cryin' Out Loud", albumId: "Southern Nights", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 4, title: "God Only Knows", albumId: "Southern Nights", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 5, title: "Sunflower", albumId: "Southern Nights", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 6, title: "Early Morning Song" , albumId: "Southern Nights", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 8, title: "(I'm Getting) Used to the Crying", albumId: "Southern Nights", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 9, title: "Let Go", albumId: "Southern Nights", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 9, title: "How High Did We Go", albumId: "Southern Nights", createdAt: new Date(), updatedAt: new Date()},

//{ trackNum: 1, title: "Enter Sandman", albumId: "Metallica", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 2, title: "Sad but True", albumId: "Metallica", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 3, title: "Holier than Thou", albumId: "Metallica", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 4, title: "The Unforgiven", albumId: "Metallica", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 5, title: "Wherever I May Roam", albumId: "Metallica", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 6, title: "Through the Never" , albumId: "Metallica", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 8, title: "Nothing Else Matters", albumId: "Metallica", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 9, title: "Of Wolf and Man", albumId: "Metallica", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 10, title: "The God That Failed", albumId: "Metallica", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 11, title: "My Friend of Misery", albumId: "Metallica", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 12, title: "The Struggle Within", albumId: "Metallica", createdAt: new Date(), updatedAt: new Date()},

//{ trackNum: 1, title: "Second Hand News", albumId: "Rumours", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 2, title: "Dreams", albumId: "Rumours", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 3, title: "Never Going Back Again", albumId: "Rumours", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 4, title: "Don't Stop", albumId: "Rumours", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 5, title: "Go Your Own Way", albumId: "Rumours", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 6, title: "Songbird" , albumId: "Rumours", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 7, title: "The Chain", albumId: "Rumours", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 8, title: "You Make Loving Fun", albumId: "Rumours", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 9, title: "I Don't Want to Know", albumId: "Rumours", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 10, title: "Oh Daddy", albumId: "Rumours", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 11, title: "Gold Dust Woman", albumId: "Rumours", createdAt: new Date(), updatedAt: new Date()},

//{ trackNum: 1, title: "Shine On You Crazy Diamond (Parts I–V)", albumId: "Wish You Were Here", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 2, title: "Welcome to the Machine", albumId: "Wish You Were Here", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 3, title: "Have a Cigar", albumId: "Wish You Were Here", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 4, title: "Wish You Were Here", albumId: "Wish You Were Here", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 5, title: "Shine On You Crazy Diamond (Parts VI–IX)", albumId: "Wish You Were Here", createdAt: new Date(), updatedAt: new Date()},

//{ trackNum: 1, title: "The Devil Made Me Do It", albumId: "Cut", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 2, title: "Future", albumId: "Cut", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 3, title: "Baby Dynamite", albumId: "Cut", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 4, title: "Last of the Mohicans", albumId: "Cut", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 5, title: "Lost and Found", albumId: "Cut", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 6, title: "Twilight Zone" , albumId: "Cut", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 7, title: "Chargin' Up My Batteries" Up My Batteries", albumId: "Cut", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 8, title: "Secrets", albumId: "Cut", createdAt: new Date(), updatedAt: new Date()},

//{ trackNum: 1, title: "Beer Never Broke My Heart", albumId: "What You See Is What You Get", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 2, title: "Refrigerator Door", albumId: "What You See Is What You Get", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 3, title: "Even Though I'm Leaving", albumId: "What You See Is What You Get", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 4, title: "Lovin' on You", albumId: "What You See Is What You Get", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 5, title: "Moon Over Mexico", albumId: "What You See Is What You Get", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 6, title: "1, 2 Many" , albumId: "What You See Is What You Get", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 7, title: "Blue Collar Boys", albumId: "What You See Is What You Get", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 8, title: "New Every Day", albumId: "What You See Is What You Get", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 9, title: "Reasons", albumId: "What You See Is What You Get", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 10, title: "Every Little Bit Helps", albumId: "What You See Is What You Get", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 11, title: "Dear Today", albumId: "What You See Is What You Get", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 12, title: "What You See Is What You Get", albumId: "What You See Is What You Get", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 13, title: "Does to Me", albumId: "What You See Is What You Get", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 14, title: "Angels Workin' Overtime", albumId: "What You See Is What You Get", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 15, title: "All Over Again", albumId: "What You See Is What You Get", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 16, title: "Nothing Like You", albumId: "What You See Is What You Get", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 17, title: "Better Together", albumId: "What You See Is What You Get", createdAt: new Date(), updatedAt: new Date()},

//{ trackNum: 1, title: "Serve the Servants", albumId: "In Utero", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 2, title: "Scentless Apprentice", albumId: "In Utero", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 3, title: "Heart-Shaped Box", albumId: "In Utero", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 4, title: "Rape Me", albumId: "In Utero", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 5, title: "Frances Farmer Will Have Her Revenge on Seattle", albumId: "In Utero", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 6, title: "Dumb" , albumId: "In Utero", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 7, title: "Very Ape", albumId: "In Utero", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 8, title: "Milk It", albumId: "In Utero", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 9, title: "Pennyroyal Tea", albumId: "In Utero", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 10, title: "Radio Friendly Unit Shifter", albumId: "In Utero", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 11, title: "Tourette's", albumId: "In Utero", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 12, title: "All Apologies", albumId: "In Utero", createdAt: new Date(), updatedAt: new Date()},

//{ trackNum: 1, title: "Knockin' Boots", albumId: "Born Here Live Here Die Here", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 2, title: "What She Wants Tonight", albumId: "Born Here Live Here Die Here", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 3, title: "Born Here Live Here Die Here", albumId: "Born Here Live Here Die Here", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 4, title: "One Margarita", albumId: "Born Here Live Here Die Here", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 5, title: "Too Drunk to Drive", albumId: "Born Here Live Here Die Here", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 6, title: "Build Me a Daddy" , albumId: "Born Here Live Here Die Here", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 7, title: "Little Less Broken", albumId: "Born Here Live Here Die Here", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 8, title: "For a Boat", albumId: "Born Here Live Here Die Here", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 9, title: "Where Are We Goin'", albumId: "Born Here Live Here Die Here", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 10, title: "Down to One", albumId: "Born Here Live Here Die Here", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 11, title: "Country Does", albumId: "Born Here Live Here Die Here", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 12, title: "Drink a Little Whiskey Down", albumId: "Born Here Live Here Die Here", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 13, title: "Waves", albumId: "Born Here Live Here Die Here", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 14, title: "Bill Dance", albumId: "Born Here Live Here Die Here", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 15, title: "Up", albumId: "Born Here Live Here Die Here", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 16, title: "Floatin' This Creek", albumId: "Born Here Live Here Die Here", createdAt: new Date(), updatedAt: new Date()},





//* Christian's


//* Owen's
