// { trackNum: #, title: "title", albumId: #, createdAt: new Date(), updatedAt: new Date()},


//* Monte's

// { trackNum: 1, title: "Is This Love", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 2, title: "No Woman, No Cry" (Live), albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 3, title: "Could You Be Loved", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 4, title: "Three Little Birds", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 5, title: "Buffalo Soldier", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 6, title: "Get Up, Stand Up", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 7, title: "Stir It Up", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 8, title: "One Love / People Get Ready", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 9, title: "I Shot the Sheriff", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 10, title: "Waiting in Vain", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 11, title: "Redemption Song", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 12, title: "Satisfy My Soul", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 13, title: "Exodus", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 14, title: "Jamming", albumId: #, createdAt: new Date(), updatedAt: new Date()},

// { trackNum: 1, title: "The District Sleeps Alone Tonight", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 2, title: "Such Great Heights", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 3, title: "Sleeping In", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 4, title: "Nothing Better", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 5, title: "Recycled Air", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 6, title: "Clark Gable", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 7, title: "We Will Become Silhouettes", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 8, title: "This Place Is a Prison", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 9, title: "Brand New Colony", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 10, title: "Natural Anthem", albumId: #, createdAt: new Date(), updatedAt: new Date()},

// { trackNum: 1, title: "Airbag", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 2, title: "Paranoid Android", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 3, title: "Subterranean Homesick Alien", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 4, title: "Exit Music (For a Film", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 5, title: "Let Down", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 6, title: "Karma Police", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 7, title: "Fitter Happier", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 8, title: "Electioneering", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 9, title: "Climbing Up the Walls", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 10, title: "No Surprises", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 11, title: "Lucky", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 12, title: "The Tourist", albumId: #, createdAt: new Date(), updatedAt: new Date()},

// { trackNum: 1, title: "Tautou", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 2, title: "Sic Transit Gloria...Glory Fades", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 3, title: "I Will Play My Game Beneath the Spin Light", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 4, title: "Okay I Believe You, But My Tommy Gun Don't", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 5, title: "The Quiet Things That No One Ever Knows", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 6, title: "The Boy Who Blocked His Own Shot", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 7, title: "Jaws Theme Swimming", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 8, title: "Me vs. Maradona vs. Elvis", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 9, title: "Guernica", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 10, title: "Good to Know That If I Ever Need Attention All I Have to Do Is Die", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 11, title: "Play Crack the Sky", albumId: #, createdAt: new Date(), updatedAt: new Date()},

// { trackNum: 1, title: "Intro", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 2, title: "Lost Ones", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 3, title: "Ex-Factor", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 4, title: "To Zion", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 5, title: "Doo Wop (That Thing)", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 6, title: "Superstar", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 7, title: "Final Hour", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 8, title: "When It Hurts So Bad", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 9, title: "I Used to Love Him", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 10, title: "Forgive Them Father", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 11, title: "Every Ghetto, Every City", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 12, title: "Nothing Even Matters", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 13, title: "Everything Is Everything", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 14, title: "The Miseducation of Lauryn Hill", albumId: #, createdAt: new Date(), updatedAt: new Date()},

// { trackNum: 1, title: "Bleed American", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 2, title: "A Praise Chorus", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 3, title: "The Middle", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 4, title: "Your House", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 5, title: "Sweetness", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 6, title: "Hear You Me", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 7, title: "If You Don't, Don't", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 8, title: "Get It Faster", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 9, title: "Cautioners", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 10, title: "The Authority Song", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 11, title: "My Sundown", albumId: #, createdAt: new Date(), updatedAt: new Date()},

// { trackNum: 1, title: "Time to Pretend", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 2, title: "Weekend Wars", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 3, title: "The Youth", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 4, title: "Electric Feel", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 5, title: "Kids", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 6, title: "4th Dimensional Transition", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 7, title: "Pieces of What", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 8, title: "Of Moons, Birds & Monsters", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 9, title: "The Handshake", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 10, title: "Future Reflections", albumId: #, createdAt: new Date(), updatedAt: new Date()},

// { trackNum: 1, title: "One More Time", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 2, title: "Aerodynamic", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 3, title: "Digital Love", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 4, title: "Harder, Better, Faster, Stronger"", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 5, title: "Crescendolls", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 6, title: "Nightvision", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 7, title: "Superheroes", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 8, title: "High Life", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 9, title: "Something About Us", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 10, title: "Voyager", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 11, title: "Veridis Quo", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 12, title: "Short Circuit", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 13, title: "Face to Face", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 14, title: "Too Long", albumId: #, createdAt: new Date(), updatedAt: new Date()},

// { trackNum: 1, title: "Bombtrack", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 2, title: "Killing in the Name", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 3, title: "Take the Power Back", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 4, title: "Settle for Nothing", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 5, title: "Bullet in the Head", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 6, title: "Know Your Enemy", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 7, title: "Wake Up", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 8, title: "Fistful of Steel", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 9, title: "Township Rebellion", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 10, title: "Freedom", albumId: #, createdAt: new Date(), updatedAt: new Date()},

// { trackNum: 1, title: "Rehab", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 2, title: "You Know I'm No Good", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 3, title: "Me & Mr Jones", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 4, title: "Just Friends", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 5, title: "Back to Black", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 6, title: "Love Is a Losing Game", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 7, title: "Tears Dry on Their Own", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 8, title: "Wake Up Alone", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 9, title: "Some Unholy War", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 10, title: "He Can Only Hold Her", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 11, title: "Addicted", albumId: #, createdAt: new Date(), updatedAt: new Date()},




//* Brad's

//{ trackNum: 1, title: "I Ain't the One", albumId: "Pronounced 'Lĕh-'nérd 'Skin-'nérd", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 2, title: "Tuesday's Gone", albumId: "Pronounced 'Lĕh-'nérd 'Skin-'nérd", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 3, title: "Gimme Three Steps", albumId: "Pronounced 'Lĕh-'nérd 'Skin-'nérd", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 4, title: "Simple Man", albumId: "Pronounced 'Lĕh-'nérd 'Skin-'nérd", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 5, title: "Mississippi Kid", albumId: "Pronounced 'Lĕh-'nérd 'Skin-'nérd", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 6, title: "Poison Whiskey", albumId: "Pronounced 'Lĕh-'nérd 'Skin-'nérd", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 7, title: "Free Bird", albumId: "Pronounced 'Lĕh-'nérd 'Skin-'nérd", createdAt: new Date(), updatedAt: new Date()},

//{ trackNum: 1, title: "I Was Made for Lovin' You", albumId: "Dynasty", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 2, title: "2,000 Man", albumId: "Dynasty", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 3, title: "Sure Know Something", albumId: "Dynasty", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 4, title: "Dirty Livin' ", albumId: "Dynasty", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 5, title: "Charisma", albumId: "Dynasty", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 6, title: "Magic Touch", albumId: "Dynasty", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 7, title: "Hard Times", albumId: "Dynasty", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 8, title: "X-Ray Eyes", albumId: "Dynasty", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 9, title: "Save Your Love", albumId: "Dynasty", createdAt: new Date(), updatedAt: new Date()},

//{ trackNum: 1, title: "Southern Nights", albumId: "Southern Nights", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 2, title: "This Is Sarah's Song", albumId: "Southern Nights", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 3, title: "For Cryin' Out Loud", albumId: "Southern Nights", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 4, title: "God Only Knows", albumId: "Southern Nights", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 5, title: "Sunflower", albumId: "Southern Nights", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 6, title: "Early Morning Song" , albumId: "Southern Nights", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 8, title: "(I'm Getting) Used to the Crying", albumId: "Southern Nights", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 9, title: "Let Go", albumId: "Southern Nights", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 9, title: "How High Did We Go", albumId: "Southern Nights", createdAt: new Date(), updatedAt: new Date()},

//{ trackNum: 1, title: "Enter Sandman", albumId: "Metallica", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 2, title: "Sad but True", albumId: "Metallica", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 3, title: "Holier than Thou", albumId: "Metallica", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 4, title: "The Unforgiven", albumId: "Metallica", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 5, title: "Wherever I May Roam", albumId: "Metallica", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 6, title: "Through the Never" , albumId: "Metallica", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 8, title: "Nothing Else Matters", albumId: "Metallica", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 9, title: "Of Wolf and Man", albumId: "Metallica", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 10, title: "The God That Failed", albumId: "Metallica", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 11, title: "My Friend of Misery", albumId: "Metallica", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 12, title: "The Struggle Within", albumId: "Metallica", createdAt: new Date(), updatedAt: new Date()},

//{ trackNum: 1, title: "Second Hand News", albumId: "Rumours", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 2, title: "Dreams", albumId: "Rumours", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 3, title: "Never Going Back Again", albumId: "Rumours", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 4, title: "Don't Stop", albumId: "Rumours", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 5, title: "Go Your Own Way", albumId: "Rumours", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 6, title: "Songbird" , albumId: "Rumours", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 7, title: "The Chain", albumId: "Rumours", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 8, title: "You Make Loving Fun", albumId: "Rumours", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 9, title: "I Don't Want to Know", albumId: "Rumours", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 10, title: "Oh Daddy", albumId: "Rumours", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 11, title: "Gold Dust Woman", albumId: "Rumours", createdAt: new Date(), updatedAt: new Date()},

//{ trackNum: 1, title: "Shine On You Crazy Diamond (Parts I–V)", albumId: "Wish You Were Here", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 2, title: "Welcome to the Machine", albumId: "Wish You Were Here", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 3, title: "Have a Cigar", albumId: "Wish You Were Here", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 4, title: "Wish You Were Here", albumId: "Wish You Were Here", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 5, title: "Shine On You Crazy Diamond (Parts VI–IX)", albumId: "Wish You Were Here", createdAt: new Date(), updatedAt: new Date()},

//{ trackNum: 1, title: "The Devil Made Me Do It", albumId: "Cut", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 2, title: "Future", albumId: "Cut", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 3, title: "Baby Dynamite", albumId: "Cut", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 4, title: "Last of the Mohicans", albumId: "Cut", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 5, title: "Lost and Found", albumId: "Cut", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 6, title: "Twilight Zone" , albumId: "Cut", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 7, title: "Chargin' Up My Batteries" Up My Batteries", albumId: "Cut", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 8, title: "Secrets", albumId: "Cut", createdAt: new Date(), updatedAt: new Date()},

//{ trackNum: 1, title: "Beer Never Broke My Heart", albumId: "What You See Is What You Get", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 2, title: "Refrigerator Door", albumId: "What You See Is What You Get", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 3, title: "Even Though I'm Leaving", albumId: "What You See Is What You Get", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 4, title: "Lovin' on You", albumId: "What You See Is What You Get", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 5, title: "Moon Over Mexico", albumId: "What You See Is What You Get", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 6, title: "1, 2 Many" , albumId: "What You See Is What You Get", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 7, title: "Blue Collar Boys", albumId: "What You See Is What You Get", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 8, title: "New Every Day", albumId: "What You See Is What You Get", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 9, title: "Reasons", albumId: "What You See Is What You Get", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 10, title: "Every Little Bit Helps", albumId: "What You See Is What You Get", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 11, title: "Dear Today", albumId: "What You See Is What You Get", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 12, title: "What You See Is What You Get", albumId: "What You See Is What You Get", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 13, title: "Does to Me", albumId: "What You See Is What You Get", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 14, title: "Angels Workin' Overtime", albumId: "What You See Is What You Get", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 15, title: "All Over Again", albumId: "What You See Is What You Get", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 16, title: "Nothing Like You", albumId: "What You See Is What You Get", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 17, title: "Better Together", albumId: "What You See Is What You Get", createdAt: new Date(), updatedAt: new Date()},

//{ trackNum: 1, title: "Serve the Servants", albumId: "In Utero", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 2, title: "Scentless Apprentice", albumId: "In Utero", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 3, title: "Heart-Shaped Box", albumId: "In Utero", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 4, title: "Rape Me", albumId: "In Utero", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 5, title: "Frances Farmer Will Have Her Revenge on Seattle", albumId: "In Utero", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 6, title: "Dumb" , albumId: "In Utero", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 7, title: "Very Ape", albumId: "In Utero", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 8, title: "Milk It", albumId: "In Utero", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 9, title: "Pennyroyal Tea", albumId: "In Utero", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 10, title: "Radio Friendly Unit Shifter", albumId: "In Utero", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 11, title: "Tourette's", albumId: "In Utero", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 12, title: "All Apologies", albumId: "In Utero", createdAt: new Date(), updatedAt: new Date()},

//{ trackNum: 1, title: "Knockin' Boots", albumId: "Born Here Live Here Die Here", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 2, title: "What She Wants Tonight", albumId: "Born Here Live Here Die Here", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 3, title: "Born Here Live Here Die Here", albumId: "Born Here Live Here Die Here", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 4, title: "One Margarita", albumId: "Born Here Live Here Die Here", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 5, title: "Too Drunk to Drive", albumId: "Born Here Live Here Die Here", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 6, title: "Build Me a Daddy" , albumId: "Born Here Live Here Die Here", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 7, title: "Little Less Broken", albumId: "Born Here Live Here Die Here", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 8, title: "For a Boat", albumId: "Born Here Live Here Die Here", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 9, title: "Where Are We Goin'", albumId: "Born Here Live Here Die Here", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 10, title: "Down to One", albumId: "Born Here Live Here Die Here", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 11, title: "Country Does", albumId: "Born Here Live Here Die Here", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 12, title: "Drink a Little Whiskey Down", albumId: "Born Here Live Here Die Here", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 13, title: "Waves", albumId: "Born Here Live Here Die Here", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 14, title: "Bill Dance", albumId: "Born Here Live Here Die Here", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 15, title: "Up", albumId: "Born Here Live Here Die Here", createdAt: new Date(), updatedAt: new Date()},
//{ trackNum: 16, title: "Floatin' This Creek", albumId: "Born Here Live Here Die Here", createdAt: new Date(), updatedAt: new Date()},


//* Christian's
//* Christian's
// { trackNum:1, title: "Intro", albumId:"The College Dropout" , createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 2, title: "We Don't Care", albumId:"The College Dropout" , createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 3, title: "Graduation Day", albumId:"The College Dropout" , createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 4, title: "All Falls Down", albumId:"The College Dropout" , createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 5, title: "I'll Fly Away", albumId:"The College Dropout" , createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 6, title: "Spaceship", albumId:"The College Dropout" , createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 7, title: "Jesus Walks", albumId:"The College Dropout" , createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 8, title: "Never Let Me Down", albumId:"The College Dropout" , createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 9, title: "Get Em High", albumId:"The College Dropout" , createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 10, title: "The Workout Plan", albumId:"The College Dropout" , createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 11, title: "The New Workout Plan", albumId:"The College Dropout" , createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 12, title: "Slow Jamz", albumId:"The College Dropout" , createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 13, title: "Breathe in Breathe Out", albumId:"The College Dropout" , createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 14, title: "School Spirit Skit 1", albumId:"The College Dropout" , createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 15, title: "School Spirit", albumId:"The College Dropout" , createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 16, title: "School Spirit (Skit 2)", albumId:"The College Dropout" , createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 17, title: "Lil Jimmy (Skit)", albumId:"The College Dropout" , createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 18, title: "Two Words", albumId:"The College Dropout" , createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 19, title: "Through The Wire", albumId:"The College Dropout" , createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 20, title: "Family Business", albumId:"The College Dropout" , createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 21, title: "Last Call", albumId:"The College Dropout" , createdAt: new Date(), updatedAt: new Date()},

//  { trackNum: 1, title: "My Collection", albumId: "HNDRXX", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 2, title: "Comin Out Strong", albumId: "HNDRXX", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 3, title: "Lookin Exotic", albumId: "HNDRXX", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 4, title: "Damage", albumId: "HNDRXX", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 5, title: "Use Me", albumId: "HNDRXX", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 6, title: "Incredible", albumId: "HNDRXX", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 7, title: "Testify", albumId: "HNDRXX", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 8, title: "Fresh Air", albumId: "HNDRXX", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 9, title: "Neva Missa Lost", albumId: "HNDRXX", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 10, title: "Keep Quiet", albumId: "HNDRXX", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 11, title: "Hallucinating", albumId: "HNDRXX", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 12, title: "I Thank U", albumId: "HNDRXX", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 13, title: "New Illuminati", albumId: "HNDRXX", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 14, title: "Turn on Me", albumId: "HNDRXX", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 15, title: "Selfish", albumId: "HNDRXX", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 16, title: "Solo", albumId: "HNDRXX", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 17, title: "Sorry", albumId: "HNDRXX", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 18, title: "PIE", albumId: "HNDRXX", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 19, title: "You Da Baddest", albumId: "HNDRXX", createdAt: new Date(), updatedAt: new Date()},

//  { trackNum: 1, title: "The Ruler's Back", albumId: "The Blueprint", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 2, title: "Takeover", albumId: "The Blueprint", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 3, title: "Izzo (H.O.V.A.)", albumId: "The Blueprint", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 4, title: "Girls,Girls,Girls", albumId: "The Blueprint", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 5, title: "Jigga That", albumId: "The Blueprint", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 6, title: "U Don't Know", albumId: "The Blueprint", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 7, title: "Hola Hovito", albumId: "The Blueprint", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 8, title: "Heart Of The City", albumId: "The Blueprint", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 9, title: "Never Change", albumId: "The Blueprint", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 10, title: "Song Cry", albumId: "The Blueprint", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 11, title: "All I Need", albumId: "The Blueprint", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 12, title: "Renegade", albumId: "The Blueprint", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 13, title: "Blueprint", albumId: "The Blueprint", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 14, title: "Lyrical Exercise", albumId: "The Blueprint", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 15, title: "Girls,Girls,Girls Pt.II", albumId: "The Blueprint", createdAt: new Date(), updatedAt: new Date()},


//  { trackNum: 1, title: "Intro", albumId: "2014 Forrest Hill Drive", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 2, title: "January 28th", albumId: "2014 Forrest Hill Drive", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 3, title: "Wet Dreamz", albumId: "2014 Forrest Hill Drive", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 4, title: "03' Adolescence", albumId: "2014 Forrest Hill Drive", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 5, title: "A Tale Of 2 Citiez", albumId: "2014 Forrest Hill Drive", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 6, title: "Fire Squad", albumId: "2014 Forrest Hill Drive", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 7, title: "St. Tropez", albumId: "2014 Forrest Hill Drive", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 8, title: "G.O.M.D", albumId: "2014 Forrest Hill Drive", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 9, title: "No Role Modelz", albumId: "2014 Forrest Hill Drive", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 10, title: "Hello", albumId: "2014 Forrest Hill Drive", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 11, title: "Apparently", albumId: "2014 Forrest Hill Drive", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 12, title: "Love Yourz", albumId: "2014 Forrest Hill Drive", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 13, title: "Note To Self", albumId: "2014 Forrest Hill Drive", createdAt: new Date(), updatedAt: new Date()},


//  { trackNum: 1, 10 Purple Summers: "title", albumId: "Still Summer In The Projects", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 2, title: "Bet I Walk", albumId: "Still Summer In The Projects", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 3, title: "Twisting The Lens", albumId: "Still Summer In The Projects", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 4, title: "Trap House", albumId: "Still Summer In The Projects", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 5, title: "Loaded", albumId: "Still Summer In The Projects", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 6, title: "Gettin Ready", albumId: "Still Summer In The Projects", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 7, title: "Change Your Mind", albumId: "Still Summer In The Projects", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 8, title: "In The Morning", albumId: "Still Summer In The Projects", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 9, title: "Wasted", albumId: "Still Summer In The Projects", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 10, title: "Grapevine", albumId: "Still Summer In The Projects", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 11, title: "Visions", albumId: "Still Summer In The Projects", createdAt: new Date(), updatedAt: new Date()},

//  { trackNum: 1, title: "TO The Top", albumId: "Too Hard", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 2, title: "Money", albumId: "Too Hard", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 3, title: "All Of a Sudden", albumId: "Too Hard", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 4, title: "Moeny Forever", albumId: "Too Hard", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 5, title: "Best Of Me", albumId: "Too Hard", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 6, title: "Ride My Wave", albumId: "Too Hard", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 7, title: "Hurry", albumId: "Too Hard", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 8, title: "Sum More", albumId: "Too Hard", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 9, title: "Going For It", albumId: "Too Hard", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 10, title: "Slow Mo", albumId: "Too Hard", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 11, title: "Trap Star", albumId: "Too Hard", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 12, title: "Eat Or Starve", albumId: "Too Hard", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 13, title: "Freestyle", albumId: "Too Hard", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 14, title: "Vision Clear", albumId: "Too Hard", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 15, title: "Dive In", albumId: "Too Hard", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 16, title: "Stick On Me", albumId: "Too Hard", createdAt: new Date(), updatedAt: new Date()},

//  { trackNum: 1, title: "Intro", albumId: "Tha Carter IV", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 2, title: "Blunt Blowin", albumId: "Tha Carter IV", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 3, title: "MegaMan", albumId: "Tha Carter IV", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 4, title: "Nighmares Of The Botton", albumId: "Tha Carter IV", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 5, title: "How To Hate", albumId: "Tha Carter IV", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 6, title: "Interlude", albumId: "Tha Carter IV", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 7, title: "John", albumId: "Tha Carter IV", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 8, title: "Atortion", albumId: "Tha Carter IV", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 9, title: "So Special", albumId: "Tha Carter IV", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 10, title: "How To Love", albumId: "Tha Carter IV", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 11, title: "President Carter", albumId: "Tha Carter IV", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 12, title: "title", It's Good: "Tha Carter IV", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 13, title: "title", Outro: "Tha Carter IV", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 14, title: "title", I Like The View: "Tha Carter IV", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 15, title: "title", Mirror: "Tha Carter IV", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 16, title: "title", Two Shots: "Tha Carter IV", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 17, title: "title", Up Up And Away: "Tha Carter IV", createdAt: new Date(), updatedAt: new Date()},

//  { trackNum: 1, : "Dreams And Nightmares", albumId: "Dreams And Nightmares", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 2, In God We Trust: "title", albumId: "Dreams And Nightmares", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 3, title: "Young & Gifted", albumId: "Dreams And Nightmares", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 5, title: "Believe It", albumId: "Dreams And Nightmares", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 6, title: "Maybach Curtains", albumId: "Dreams And Nightmares", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 7, title: "Amen", albumId: "Dreams And Nightmares", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 8, title: "Young Kings", albumId: "Dreams And Nightmares", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 9, title: "Lay Up", albumId: "Dreams And Nightmares", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 10, title: "Tony Story", albumId: "Dreams And Nightmares", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 11, title: "Who You're Around", albumId: "Dreams And Nightmares", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 12, title: "Polo & Shell Tops", albumId: "Dreams And Nightmares", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 13, title: "Rich & Famous", albumId: "Dreams And Nightmares", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 14, title: "Real Come First", albumId: "Dreams And Nightmares", createdAt: new Date(), updatedAt: new Date()},


//  { trackNum: 1, title: "Unethical & Deceitful", albumId: "Beyond Bulletproof", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 2, title: "So Lonely", albumId: "Beyond Bulletproof", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 3, title: "Body Count", albumId: "Beyond Bulletproof", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 4, title: "Betrayed", albumId: "Beyond Bulletproof", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 5, title: "Bulltproofly", albumId: "Beyond Bulletproof", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 6, title: "Bozy To Men", albumId: "Beyond Bulletproof", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 7, title: "I Ain't Perfect", albumId: "Beyond Bulletproof", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 8, title: "Can't Let You Go", albumId: "Beyond Bulletproof", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 9, title: "Pricetag", albumId: "Beyond Bulletproof", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 10, title: "The Homies wanna Know", albumId: "Beyond Bulletproof", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 11, title: "Off The Muscle", albumId: "Beyond Bulletproof", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 12, title: "Big Homie From The Hood", albumId: "Beyond Bulletproof", createdAt: new Date(), updatedAt: new Date()},

//  { trackNum: 1, title: "How I Live", albumId: "38 Baby", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 2, title: "38 Baby", albumId: "38 Baby", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 3, title: "Hell And Back", albumId: "38 Baby", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 4, title: "Ride Out", albumId: "38 Baby", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 5, title: "H.A.M", albumId: "38 Baby", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 6, title: "Gravity", albumId: "38 Baby", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 7, title: "Up In Blood", albumId: "38 Baby", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 8, title: "My Kind Of Night", albumId: "38 Baby", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 9, title: "What I Was Taught", albumId: "38 Baby", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 10, title: "Like Me", albumId: "38 Baby", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 11, title: "For It", albumId: "38 Baby", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 12, title: "Down Chick", albumId: "38 Baby", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 13, title: "I Ain't Hiding", albumId: "38 Baby", createdAt: new Date(), updatedAt: new Date()},
//  { trackNum: 14, title: "They Ain't With Me", albumId: "38 Baby", createdAt: new Date(), updatedAt: new Date()},


//* Owen's


// { trackNum: 1, title: "Get Up 10", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 2, title: "Drip", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 3, title: "Bickenhead", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 4, title: "Bodak Yellow", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 5, title: "Be Careful", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 6, title: "Best Life", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 7, title: "I Like It", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 8, title: "Ring", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 9, title: "Money Bag", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 10, title: "Bartier Cardi", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 11, title: "She Bad", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 12, title: "Thru Your Phone", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 13, title: "I do", albumId: #, createdAt: new Date(), updatedAt: new Date()},

// { trackNum: 1, title: "The Time We Faced Doom", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 2, title: "DOOMsday", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 3, title: "Rhymes Like Dimes", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 4, title: "The Finest", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 5, title: "Back in the Days", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 6, title: "Go With the Flow", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 7, title: "Tick, Tick", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 8, title: "Red and Gold", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 9, title: "The Hands of Doom", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 10, title: "Who You Think I Am?", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 11, title: "Doom, Are You Awake?", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 12, title: "Hey!", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 13, title: "Operation: Greenbacks", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 14, title: "The M.I.C.", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 15, title: "The Mystery of Doom", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 16, title: "Dead Bent", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 17, title: "Gas Drawls", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 18, title: "?", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 19, title: "Hero vs. Villain", albumId: #, createdAt: new Date(), updatedAt: new Date()},

// { trackNum: 1, title: "Intro", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 2, title: "Things Done Changed", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 3, title: "Gimme the Loot", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 4, title: "Machine Gun Funk", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 5, title: "Warning", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 6, title: "Ready To Die", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 7, title: "One More Chance", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 8, title: "Fuck Me", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 9, title: "Juicy", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 10, title: "Everyday Struggle", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 11, title: "Me and My B*tch", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 12, title: "Big Poppa", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 13, title: "Respect", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 14, title: "Friend of Mine", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 15, title: "Unbelievable", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 16, title: "Suicidal Thoughts", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 17, title: "Who Shot Ya", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 18, title: "Just Playing", albumId: #, createdAt: new Date(), updatedAt: new Date()},

// { trackNum: 1, title: "La Rue", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 2, title: "Automne", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 3, title: "L'enfant Samba", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 4, title: "Troupeau Bleu", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 5, title: "Prelude A '60 Round'", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 6, title: "Go Round", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 7, title: "Chanson D'un Jour D'hiver", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 8, title: "Mary Et Jeff", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 9, title: "Huit Octobre 1971", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 10, title: "Sabbat (1ere Partie)", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 11, title: "Sabbat (2ere Partie)", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 12, title: "Sabbat (3ere Partie)", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 13, title: "Madbass", albumId: #, createdAt: new Date(), updatedAt: new Date()},

// { trackNum: 1, title: "Part 1: 'Acknowledgement'", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 2, title: "Part 2: 'Resolution'", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 3, title: "Part 3: 'Pursuance'/ Part 4: 'Psalm'", albumId: #, createdAt: new Date(), updatedAt: new Date()},

// { trackNum: 1, title: "Choose Your Weapon", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 2, title: "Shaolin Monk Motherfunk", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 3, title: "Laputa", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 4, title: "Creations Part One", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 5, title: "Borderline with My Atoms", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 6, title: "Breathing Underwater", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 7, title: "Cicada", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 8, title: "Swamp Thing", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 9, title: "Fingerprints", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 10, title: "Jekyll", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 11, title: "Prince Minikid", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 12, title: "Atari", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 13, title: "By Fire", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 14, title: "Creations Part Two", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 15, title: "The Lung", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 16, title: "Only Time All the Time: Making Friends", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 17, title: "Molasses", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 18, title: "Building a Ladder", albumId: #, createdAt: new Date(), updatedAt: new Date()},

// { trackNum: 1, title: "I Want You (Vocal)", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 2, title: "Come Live with Me Angel", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 3, title: "After the Dance (Instrumental)", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 4, title: "Feel All My Love Inside", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 5, title: "I Wanna Be Where You Are", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 6, title: "I Want You (Intro Jam)", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 7, title: "All the Way Around", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 8, title: "Since I Had You", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 9, title: "Soon I'll Be Loving You Again", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 10, title: "I Want You (Intro Jam) Ross, Ware", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 11, title: "After the Dance (Vocal)", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 12, title: "I Want You (Vocal) (Promo Only Version)", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 13, title: "I Want You (Instrumental)", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 14, title: "Strange Love (Feel All My Love Inside)", albumId: #, createdAt: new Date(), updatedAt: new Date()},

// { trackNum: 1, title: "Shining Star", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 2, title: "That's the Way of the World", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 3, title: "Happy Feelin'", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 4, title: "All About Love", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 5, title: "Yearnin' Learnin'", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 6, title: "Reasons", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 7, title: "Africano", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 8, title: "See the Light", albumId: #, createdAt: new Date(), updatedAt: new Date()},

// { trackNum: 1, title: "World Keeps Turnin' (intro)", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 2, title: "Bump It", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 3, title: "Back in the Day (Puff)", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 4, title: "I Want You", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 5, title: "Woo", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 6, title: "The Grind", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 7, title: "Danger", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 8, title: "Think Twice", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 9, title: "Love of my Life Worldwide", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 10, title: "World Keeps Turnin' (outro)", albumId: #, createdAt: new Date(), updatedAt: new Date()},


// { trackNum: 1, title: "Special to Me'", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 2, title: "My Flame", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 3, title: "Love Won't Wait", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 4, title: "Can't Say Goodbye", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 5, title: "Come to Me", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 6, title: "What You Won't Do for Love", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 7, title: "Kalimba Song", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 8, title: "Take Me Back to Then", albumId: #, createdAt: new Date(), updatedAt: new Date()},
// { trackNum: 9, title: "Down for the Third Time", albumId: #, createdAt: new Date(), updatedAt: new Date()},
